/*
 * NVIC.h
 *
 *  Created on: Sep 10, 2024
 *      Author: LENOVO
 */

#ifndef NVIC_INTERFACE_H
#define NVIC_INTERFACE_H

typedef enum
{
	FIRST_ELEMENT = -1,
	WWDG,
	EXTI16_PVD,
	EXTI21_TAMP_STAMP,
	EXTI22_RTC_WKUP,
	FLASH_GLOBAL,
	RCC_GLOBAL,
	EXTI0,
	EXTI1,
	EXTI2,
	EXTI3,
	EXTI4,
	DMA1_STREAM0,
	DMA1_STREAM1,
	DMA1_STREAM2,
	DMA1_STREAM3,
	DMA1_STREAM4,
	DMA1_STREAM5,
	DMA1_STREAM6,
	ADC_GLOBAL,
	EXTI9_5 = 23,
	TIM1_BRK_TIM9,
	TIM1_UP_TIM10,
	TIM1_TRG_COM_TIM11,
	TIM1_CC,
	TIM2_GLOBAL,
	TIM3_GLOBAL,
	TIM4_GLOBAL,
	I2C1_EV,
	I2C1_ER,
	I2C2_EV,
	I2C2_ER,
	SPI1_GLOBAL,
	SPI2_GLOBAL,
	USART1_GLOBAL,
	USART2_GLOBAL,
	EXTI15_10 = 40,
	EXTI17_RTC_ALARM,
	EXTI18_OTG_FS_WKUP,
	DMA1_STREAM7 = 47,
	SDIO_GLOBAL = 49,
	TIM5_GLOBAL,
	SPI3_GLOBAL,
	DMA2_STREAM0 = 56,
	DMA2_STREAM1,
	DMA2_STREAM2,
	DMA2_STREAM3,
	DMA2_STREAM4,
	OTG_FS_GLOBAL = 67,
	DMA2_STREAM5,
	DMA2_STREAM6,
	DMA2_STREAM7,
	USART6_GLOBAL,
	I2C3_EV,
	I2C_ER,
	FPU_GLOBAL = 81,
	SPI4_GLOBAL = 84,
	LAST_ELEMENT
}IRQ_t;



uint8_t NVIC_u8Enable(IRQ_t IRQNum);
uint8_t NVIC_u8Disable(IRQ_t IRQNum);
uint8_t NVIC_u8SetPendingFlag(IRQ_t IRQNum);
uint8_t NVIC_u8ClearPendingFlag(IRQ_t IRQNum);
uint8_t NVIC_GetActiveFlag(IRQ_t IRQNum, uint8_t* Val);


#endif /* NVIC_INTERFACE_H_ */
